name: Build Vue
on:
  push:
    branches: [main]
permissions:
  id-token: write
  pages: write
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Vue App to Github Pages
        uses: dencee/VuePagesAction@v1.0.0
        env:
          VITE_REMOTE_API: ${{vars.VITE_REMOTE_API}}
